### ISSUE TITLE
Demo camera trajectory

### ISSUE THREAD

**Issue by kam1107** [cmusatyalab/mega-nerf#14]
Hi, I would like to know how did you set the camera trajectory for your demo? Could you provide a script for that? Many thanks!

**Comment by hturki** [comment]
I don't have a great way of doing this in the repo itself. For some of the old videos I played around with camera poses I found playing with the mega-nerf-viewer, and for some other videos I used the excellent tooling available in https://github.com/NVlabs/instant-ngp. I'd recommend giving the latter a spin

**Comment by xingyi-li** [comment]
Hi @hturki, thanks for clarifying! I have played around with instant-ngp recently, but I still have 3 questions:

1. Are the camera poses mega-nerf used identical to those instant-ngp used? (I don't think they are the same because mega-nerf utilized pixsfm, while instant-ngp only used colmap) If not, then why does it possible to use the camera path editor of instant-ngp to generate camera poses of mega-nerf?
2. How do I convert the base_cam.json produced by the camera path editor of instant-ngp to the camera poses that mega-nerf expects?
3. Also, in `render_images.py`, besides `poses.txt` and `intrinsics.txt`, there is an `embeddings.txt` to be provided. Does it aim to specify which `embedding_a` to be used?

Many thanks!
